# language: haskell

env:
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install alex-3.1.7 happy-1.19.5 cabal-install-1.24 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal-1.24 update
 - cabal-1.24 install --only-dependencies --enable-tests

script:
 - make sdist
 - cd dist
 - tar xvzf alex-*.tar.gz
 - cd alex-*/
 - cabal-1.24 configure --enable-tests
 - cabal-1.24 build
 - cabal-1.24 test
